### Numpy

##### Numpy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np

## create arrays using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# Reshaping
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)
print(arr2)

arr3 = np.array([1,2,3,4,6,5])
arr3 = arr3.reshape(2,3)
print(arr3)

[[1 2 3 4 5]]
[[1 2 3]
 [4 6 5]]


In [17]:
#2D array
arr4 = np.array([[1,2,3,4,6,5], [1,2,3,4,6,5]])
print(arr4)
print(arr4.shape)


[[1 2 3 4 6 5]
 [1 2 3 4 6 5]]
(2, 6)


In [ ]:
ans = np.arange(0,10,2).reshape(5,1) 
## 0-> start, 10 -> end, 2 -> difference, shape = (5->row,1->coloumn)
print(ans)


# ans2 = np.arange(0,100,15).reshape(7,1)
# print(ans2)

[[0]
 [2]
 [4]
 [6]
 [8]]
